### ISSUE TITLE
Q : Why am I getting the error 'Bandwidth is too low' on iOS + Safari or Android + Samsung Browser ?

### ISSUE THREAD

**Issue by TronchDeYack** [opentok/opentok-network-test-js#179]
Hi everyone,

We use opentok video services and we have a connectivity test that used opentok-network-test-js. I don't know why but every time we call ```testConnectivity()``` function, we get an error 'Bandwidth is too low'. It is odd because on Android + Chrome mobile, we don't get this error.

I have test on [https://tokbox.com/developer/tools/precall/](https://tokbox.com/developer/tools/precall/) and there is no problem (I don't know if this page is using opentok-network-test).

Could you help me to understand what happens ?

Thank you.

**Comment by rhainer** [comment]
There is a new version of the opentok-network-test-js node module that is about to be released (likely today or Monday). It is currently available in beta. The Precall Tool website is based on the beta.2 version of the node module.

**Comment by isshakes** [comment]
I can confirm as I was having the same issue. After I upgraded the beta.2 version and it's not throwing me that error anymore.

**Comment by isshakes** [comment]
I can confirm, because I was experiencing the same issue. I upgraded to the beta.2 version and the problem went away.

**Comment by TronchDeYack** [comment]
Thank you, I will upgrade to the beta.2 and see if the problem is solved ! 👍

**Comment by TronchDeYack** [comment]
The problem is solved, thank you :)
