### ISSUE TITLE
Argument of type 'typeof OT' is not assignable to parameter of type 'Client'.

### ISSUE THREAD

**Issue by ngdev1995** [opentok/opentok-network-test-js#180]
import { OT } from "opentok-network-test-js/dist/NetworkTest/types/opentok"; not working
import * as OT from "@opentok/client"; not working

new NetworkTest(OT, { // OT giving error  Argument of type 'typeof OT' is not assignable to parameter of type 'Client'. how to resolve this im using this in angular
      apiKey: apiKey,
      sessionId: sessionId, // Add a test session ID for that project
      token: token, // Add a token for that session here
    });

**Comment by cnadeau** [comment]
🤔 according to [this test](https://github.com/opentok/opentok-network-test-js/blob/00d18222a1e36496d5d23db22c2644f721a7fe7f/test/NetworkTest.spec.ts#L31), it should be `import * as OT from '@opentok/client`

**Comment by cnadeau** [comment]
Found how to import it from TypeScript:

```
import '@opentok/client';
declare var OT: any;
```

**Comment by dmitryshur** [comment]
I'm sorry, but declaring OT as any is not a solution. there is a type error here and its in the `ScreenSharingCapabilityResponse` type

**Comment by jgbpercy** [comment]
Please see [this stackblitz](https://stackblitz.com/edit/typescript-i7vxpm?file=index.ts) for a minimal reproduction.
