### ISSUE TITLE
Usage problem in Angular14 library

### ISSUE THREAD

**Issue by iulianmids** [opentok/opentok-network-test-js#234]
imported in an Angular Library and I cannot get pass this
opentok_network_test_js__WEBPACK_IMPORTED_MODULE_0__ is not a constructor
![image](https://user-images.githubusercontent.com/6607692/218143214-7c90aec1-6258-4c2c-8a05-cae969108024.png)

**Comment by vona-ben** [comment]
Hi @iulianmids 
Could you share how you import the library?

`import Foo from 'some-library/Foo' `-> `import { Foo } from 'some-library'`;
