### ISSUE TITLE
Issue with npm package

### ISSUE THREAD

**Issue by jonathanwmaddison** [opentok/opentok-network-test-js#61]
Hey there, I was excited to find this package and use it to help out with testing network quality for an opentok implementation. However, I am having issues importing the package into our React project.

I noticed that the current package that is installed via `npm install opentok-network-test-js`, the distribution does not appear to be in working condition. My project's webpack fails to build due to missing packages in the opentok-network-test-js dist folder:
<img width="561" alt="screen shot 2018-05-31 at 12 39 54 pm" src="https://user-images.githubusercontent.com/22892848/40795334-c2991f66-64cf-11e8-9223-1c430872ae3f.png">

Is there any other information I could provide that would be helpful? Thanks!

**Comment by krokhale** [comment]
I am having the same issue, fs is a package available on the server, not on the front end, unless i am wrong.

Isn't this supposed to be used in the browser.

**Comment by jonathanwmaddison** [comment]
I found one way to clear out a couple errors with fs and net, add this to your webpack.config.
```
    node: {
      fs: 'empty',
      net: 'empty',
    },
```

However, I'm still getting a variety of other errors on the build:
<img width="712" alt="screen shot 2018-06-05 at 1 53 37 pm" src="https://user-images.githubusercontent.com/22892848/40993556-f090a4ce-68c7-11e8-938b-48020267d089.png">

**Comment by krokhale** [comment]
Yeah those look like more of server side dependencies. The dev team here might need to clarify the usage here.

**Comment by jonathanwmaddison** [comment]
I found the issue, in webpack.config.js the target is set to node, removing this allows the build to work in my react project.

**Comment by adrice727** [comment]
Hi @jonathanwmaddison.  You're correct.  The change was just merged into `develop` as part of https://github.com/opentok/opentok-network-test-js/pull/66 and will be in the `1.1.0` release.

**Comment by jonathanwmaddison** [comment]
solved in #66, thanks guys!

**Comment by krokhale** [comment]
Not sure what was merged/changed, but this continues to be an issue. Following the exact steps as documented in the readme:
  - npm Installed.
  - Importing using ES6 in React
  - Getting a window is not defined when i try to instantiate NetworkTest
  - Is there some extra webpack config that is not documented in the readme?

Thanks.
