### ISSUE TITLE
Enable Safari for testQuality in isSupportedBrowser

### ISSUE THREAD

**Issue by jonathanwmaddison** [opentok/opentok-network-test-js#73]
I've been working with this very helpful library, and would love to be able to use the quality test on safari mobile and safari web. I  found that adding Safari to the isSupportedBrowser array allows the quality test to run, as long as I am passing it credentials for a tokbox Safari project. Accuracy seems on par with other browsers (though MOS estimate seems inconsistent). 

I think perhaps in the testQuality method we might be able to pass in an option for Safari compatible projects i.e. testQuality({isSafariProject: true}) and then add Safari to this list if that is true: https://github.com/opentok/opentok-network-test-js/blob/eb5730e16d08bf21b343afc3e7ef9dcfd6d75b73/src/NetworkTest/testQuality/helpers/isSupportedBrowser.ts#L53

I could work on a PR for this, or perhaps you guys have already done this.

**Comment by adrice727** [comment]
We need to look at whether or not any adjustments need to be made to how the MOS estimate is calculated for `H.264` video.  I'll post an update early next week after we have a little time to look into it.

**Comment by adrice727** [comment]
@jonathanwmaddison If you want to make a PR, that would be great.  I think that for now we can just add a note to the README stating that the Safari results may not be completely accurate.  We can look at adjusting the score when we have time.

**Comment by jeffswartz** [comment]
v2.0.0 of the module now includes support for Safari in the `testQuality()` method.

**Comment by jonathanwmaddison** [comment]
@jeffswartz That's great, thank you both. Looking forward to using it.
