### ISSUE TITLE
Test duration and abort feature

### ISSUE THREAD

**Issue by hannes-md** [opentok/opentok-network-test-js#78]
Hi, I'm looking for two features that would help me a lot:

1. Ability to set duration for the test. I realise that the longer it runs the more reliable the results but 30 seconds is a long time. A nice approach would be to set `getStatsVideoAndAudioTestDuration` or something like it from the init method:
```
const otNetworkTest = new OTNetworkTest(OT, {
      apiKey: apiKey,
      sessionId: precallSessionId,
      token: precallToken,
      testDuration: myDuration,
    });
```

2. Ability to abort the test, closing everything down nicely, without having to navigate away. As it is now, in our spa application it just goes on behind the scene which is ofc not optimal. I suggest something simple like:
```
otNetworkTest.Cancel();
```

Hope this finds it's way into your very nice module. 
Thanks

/Hannes

**Comment by jeffswartz** [comment]
Hey, @hannes-md. Thanks for the recommendations. We have a new version, v2.0.0, which includes a `timeout` option and a `stop()` method.
