### ISSUE TITLE
How to use this with AngularJS and Webpack

### ISSUE THREAD

**Issue by slpn1** [opentok/opentok-network-test-js#84]
I'm sure this is me being a chump, but I am using it the way described in the readme:

```
const OTNetworkTest = require('opentok-network-test-js');

const otNetworkTest = new OTNetworkTest(OT, {
            apiKey: roomData.apiKey, // Add the API key for your OpenTok project here.
            sessionId: roomData.sessionId, // Add a test session ID for that project
            token: roomData.token // Add a token for that session here
          });

```
But I get this error. I have tried every combination I can think of.

`angular.js:13920 TypeError: OTNetworkTest is not a constructor`

Thanks,
Simon

**Comment by jeffswartz** [comment]
You need to use this (adding `.default`):

Thinking about opentok-network-test-js issue #84. The short answer is that the correct code is this (with `.default` at the end):

```require('opentok-network-test-js').default```

I will correct the readme. Thanks, @slpn1.

**Comment by slpn1** [comment]
Thanks! Working now.

**Comment by johnjbateman** [comment]
@slpn1 Just curious, did you get all of this test working in AngularJS?  This is fully compatible?

**Comment by slpn1** [comment]
@johnjbateman Hi John. Yes this is working fine with Angular JS 1.5.8.

**Comment by johnjbateman** [comment]
Thanks @slpn1 

I am having trouble getting the NetworkTest object in my controller.  I am messing with RequireJS, but will Angular do this instead?  Do you happen to have any snippets of how to wire up this correctly?

```
const OTNetworkTest = require('opentok-network-test-js').default;
```

I keep getting this error:

```
Module name has not been loaded yet for context: _. Use require([])
```

I am going dow nthe rabbit hole in RequireJS and not having luck.  

Thanks for the reply!

**Comment by slpn1** [comment]
@johnjbateman I have exactly the same code as you and it works fine, but I am using Webpack not RequireJS for module handling. I don't know much about RequireJS but looking at the docs [here](https://requirejs.org/docs/api.html#jsfiles) it looks like you need to pass an array to require, not a string. That matches with error you are receiving.

**Comment by johnjbateman** [comment]
OK, I will check into WebPack and see if that helps at all.  I have not used RequireJS before this.

**Comment by johnjbateman** [comment]
@slpn1 Any chance you can share a snippet of your webpack.config.js?
