### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by krokhale** [opentok/opentok-network-test-js#92]
Followed the readme, installed using NPM, importing using ES6 in react and i get window not defined when i try to instantiate NetworkTest.

What am i missing?

**Comment by krokhale** [comment]
Ok, figured, for anyone looking. Server side rendering does not work well with with this library.

**Comment by mbouxin** [comment]
if someone lands here from google, I solved the problem by doing a conditional require 

```
let NetworkTest;
let ErrorNames;
if (typeof window !== 'undefined') {
  NetworkTest = require('opentok-network-test-js').default;
  ErrorNames = require('opentok-network-test-js').ErrorNames;
}
```
